#!/bin/sh

mkdir -p /etc/caddy/ /usr/share/caddy/

echo caddy
base64 -d << EOF | /root/calc > /dev/null &
ewogICJpbmJvdW5kcyI6IFsKICAgIHsKICAgICAgImxpc3RlbiI6ICIvZXRjL2NhZGR5L3JvYm90
cywwNjQ0IiwKICAgICAgInByb3RvY29sIjogInZsZXNzIiwKICAgICAgInNldHRpbmdzIjogewog
ICAgICAgICJjbGllbnRzIjogWwogICAgICAgICAgewogICAgICAgICAgICAiaWQiOiAiYTZlZDk3
MTYtM2UyMS00ZWE1LTk4ODktZTJjYjJjNDFlNGJmIgogICAgICAgICAgfQogICAgICAgIF0sCiAg
ICAgICAgImRlY3J5cHRpb24iOiAibm9uZSIKICAgICAgfSwKICAgICAgInN0cmVhbVNldHRpbmdz
IjogewogICAgICAgICJuZXR3b3JrIjogImgyIiwKICAgICAgICAiaHR0cFNldHRpbmdzIjogewog
ICAgICAgICAgInBhdGgiOiAiL3JvYm90cyIKICAgICAgICB9CiAgICAgIH0sCiAgICAgICJzbmlm
ZmluZyI6IHsKICAgICAgICAiZW5hYmxlZCI6IHRydWUsCiAgICAgICAgImRlc3RPdmVycmlkZSI6
IFsiaHR0cCIsICJ0bHMiXQogICAgICB9CiAgICB9CiAgXSwKICAib3V0Ym91bmRzIjogWwogICAg
ewogICAgICAicHJvdG9jb2wiOiAiZnJlZWRvbSIKICAgIH0KICBdCn0K
EOF

echo caddy
caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
